apiVersion: apps/v1
kind: Deployment
metadata:
  name: animalphoto
  labels:
    app: animal
spec:
  replicas: 2
  selector:
    matchLabels:
      app: animal
  template:
    metadata:
      name: animalphoto
      labels:
        app: animal
    spec:
      containers:
      - name: animal
        image: nginx
        ports:
        - containerPort: 80
---
#creating a service for this deployment
kind: Service
apiVersion: v1
metadata:
  name: animalphoto
spec:
  selector:
    app: animal
  type: NodePort
  ports:
  - port: 80
    targetPort: 80
    #nodePort: 31000
